### ISSUE TITLE
Heroku Deploying issue

### ISSUE THREAD

**Issue by charindithjaindu** [megatron0000/heroku-vnc#3]
![image](https://user-images.githubusercontent.com/75799963/119173956-99484880-ba85-11eb-974c-56d1b61e5dc3.png)

**Comment by Agamya-Samuel** [comment]
yes @charindithjaindu this happens because, @megatron0000 has already said, team viewer and OBS not working, and during deployment, its trying to get packages for them, but the links are invalid thru which its trying to get them.
Use mine fork, I have removed TV and OBS from it https://github.com/agamya-samuel/heroku-vnc
IT works perfectly.
![image](https://user-images.githubusercontent.com/48693970/119551486-52c15980-bdb7-11eb-8577-ff1cae6f8f0d.png)

**Comment by charindithjaindu** [comment]
> yes @charindithjaindu this happens because, @megatron0000 has already said, team viewer and OBS not working, and during deployment, its trying to get packages for them, but the links are invalid thru which its trying to get them.
> Use mine fork, I have removed TV and OBS from it https://github.com/agamya-samuel/heroku-vnc
> IT works perfectly.
> ![image](https://user-images.githubusercontent.com/48693970/119551486-52c15980-bdb7-11eb-8577-ff1cae6f8f0d.png)

thanks bro
